-- MySQL Script generated by MySQL Workbench
-- Tue Sep 29 13:42:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema PlaceMyBet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PlaceMyBet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PlaceMyBet` DEFAULT CHARACTER SET utf8 ;
USE `PlaceMyBet` ;

-- -----------------------------------------------------
-- Table `PlaceMyBet`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlaceMyBet`.`Eventos` (
  `Identificador_evento` INT NOT NULL AUTO_INCREMENT,
  `EquipoLocal` VARCHAR(25) NOT NULL,
  `EquipoVisitante` VARCHAR(25) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`Identificador_evento`));
-- -----------------------------------------------------
-- Table `PlaceMyBet`.`Mercados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlaceMyBet`.`Mercados` (
  `id_mercado` INT NOT NULL AUTO_INCREMENT,
  `OverUnder` DOUBLE NOT NULL,
  `CuotaOver` DOUBLE NOT NULL,
  `CuotaUnder` DOUBLE NOT NULL,
  `DineroApostadoOver` DOUBLE NOT NULL,
  `DineroApostadoUnder` DOUBLE NOT NULL,
  `Eventos_Identificador_evento` INT NOT NULL,
  PRIMARY KEY (`id_mercado`),
  CONSTRAINT `fk_Mercado_Eventos1`
    FOREIGN KEY (`Eventos_Identificador_evento`)
    REFERENCES `PlaceMyBet`.`Eventos` (`Identificador_evento`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `PlaceMyBet`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlaceMyBet`.`Usuarios` (
  `Email` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido` VARCHAR(25) NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`Email`));



-- -----------------------------------------------------
-- Table `PlaceMyBet`.`Apuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlaceMyBet`.`Apuestas` (
  `id_apuesta` INT NOT NULL AUTO_INCREMENT,
  `MercadoOverUnder` DOUBLE NOT NULL,
  `TipoOverUnder` VARCHAR(15) NOT NULL,
  `Cuota` DOUBLE NOT NULL,
  `DineroApostado` DOUBLE NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Mercado_id_mercado` INT NOT NULL,
  `Usuario_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_apuesta`),
  CONSTRAINT `fk_Apuesta_Mercado1`
    FOREIGN KEY (`Mercado_id_mercado`)
    REFERENCES `PlaceMyBet`.`Mercados` (`id_mercado`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Apuesta_Usuario1`
    FOREIGN KEY (`Usuario_Email`)
    REFERENCES `PlaceMyBet`.`Usuarios` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `PlaceMyBet`.`Cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlaceMyBet`.`Cuentas` (
  `NumTajeta` BIGINT(16) NOT NULL,
  `NombreBanco` VARCHAR(25) NOT NULL,
  `Saldo` DOUBLE NOT NULL,
  `Usuarios_Email` VARCHAR(45) NULL,
  PRIMARY KEY (`NumTajeta`),
  CONSTRAINT `fk_Cuentas_Usuarios1`
    FOREIGN KEY (`Usuarios_Email`)
    REFERENCES `PlaceMyBet`.`Usuarios` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Data for table `PlaceMyBet`.`Eventos`
-- -----------------------------------------------------
INSERT INTO `PlaceMyBet`.`Eventos` (`Identificador_evento`, `EquipoLocal`, `EquipoVisitante`, `Fecha`) VALUES (1, 'Valencia', 'Español', '2020-09-23');
-- -----------------------------------------------------
-- Data for table `PlaceMyBet`.`Mercados`
-- -----------------------------------------------------
INSERT INTO `PlaceMyBet`.`Mercados` (`id_mercado`, `OverUnder`, `CuotaOver`, `CuotaUnder`, `DineroApostadoOver`, `DineroApostadoUnder`, `Eventos_Identificador_evento`) VALUES (1, 1.5, 26.45, 12.5, 100, 35, 1);
INSERT INTO `PlaceMyBet`.`Mercados` (`id_mercado`, `OverUnder`, `CuotaOver`, `CuotaUnder`, `DineroApostadoOver`, `DineroApostadoUnder`, `Eventos_Identificador_evento`) VALUES (2, 2.5, 12.45, 17.75, 45, 25, 1);
INSERT INTO `PlaceMyBet`.`Mercados` (`id_mercado`, `OverUnder`, `CuotaOver`, `CuotaUnder`, `DineroApostadoOver`, `DineroApostadoUnder`, `Eventos_Identificador_evento`) VALUES (3, 3.5, 8.5, 45.5, 12, 95, 1);
-- -----------------------------------------------------
-- Data for table `PlaceMyBet`.`Usuarios`
-- -----------------------------------------------------
INSERT INTO `PlaceMyBet`.`Usuarios` (`Email`, `Nombre`, `Apellido`, `edad`) VALUES ('juan@gmail.com', 'juan', 'lujan', 33);
-- -----------------------------------------------------
-- Data for table `PlaceMyBet`.`Apuestas`
-- -----------------------------------------------------
INSERT INTO `PlaceMyBet`.`Apuestas` (`id_apuesta`, `MercadoOverUnder`, `TipoOverUnder`, `Cuota`, `DineroApostado`, `Fecha`, `Mercado_id_mercado`, `Usuario_Email`) VALUES (1, 1.5, 'over', 26.45, 13, '2020-09-22', 1, 'juan@gmail.com');
-- -----------------------------------------------------
-- Data for table `PlaceMyBet`.`Cuentas`
-- -----------------------------------------------------
INSERT INTO `PlaceMyBet`.`Cuentas` (`NumTajeta`, `NombreBanco`, `Saldo`, `Usuarios_Email`) VALUES (12365486541236, 'santander', 1255, NULL);
